name: 'Issue Blog'
description: 'Tiny Blog based on github issues'
author: '@bxb100 aka John Bi'
inputs:
  github_token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  blog_author:
    description: The author of the blog
    default: ${{ github.repository_owner }}
    required: false
  md_header:
    description: The header of content
    default: |
      ## GitLog
      My personal blog using issues and GitHub Actions [RSS Feed](https://raw.githubusercontent.com/${{ github.repository }}/master/feed.xml)
    required: false
  blog_image_url:
    description: The image url of the blog
    default: "https://cdn.jsdelivr.net/gh/${{ github.repository }}/blog.png"
    required: false
  blog_url:
    description: The blog deploy url
    default: "https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}"
    required: false
  issue_number:
    description: The event issue number
    default: ${{ github.event.issue.number }}
    required: false
  recent_limit:
    description: The number of recent issues to display
    required: false
    default: '10'
  anchor_number:
    description: The number of issues to display
    required: false
    default: '5'
  links_title:
    description: The title of the links section
    required: false
    default: 'Links'
  recent_title:
    description: The title of the recent issues group
    required: false
    default: 'Recent'
  top_title:
    description: The title of the top issues group
    required: false
    default: 'Top'
  unlabeled_title:
    description: The title of the unlabeled issues group
    required: false
    default: 'Reverie'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/post/index.js'
branding:
  icon: 'edit-3'
  color: 'blue'
